name: Deploy demo page

on:
  push:
    branch: 2-example-project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Instal dependencies
        run:
          npm i

      - name: Build project
        run:
          npm run-script build-prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
